---
title: "About"
description: |
  A bit of background. 

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

  
  Anastasia attended University of California, Los Angeles, pursuing a Bachelors of Science in Biology, and a minor in Environmental Systems and Society. While at UCLA, she pursued a number of activities including walking on to the Division I Beach Volleyball team and helping to revive the on campus Farmers Market as the Director of Finance and Education. Anastasia fostered her love of research working in the Department of Psychiatry & Biobehavioral Sciences for three years where she developed her own research project studying therapeutic strategies to combat toxic ⍺-synuclein oligomers characteristic to Parkinson’s disease, and contributed to a larger study published in *Journal of Neuroscience Research*. Halfway through college Anastasia enrolled at Lincoln University on the South Island of New Zealand to complete coursework for her minor and backpack through the country. 

  After graduating and taking time off to travel, she applied to NASA DEVELOP, a dual capacity building program under NASA's Applied Sciences Division. At the Fort Collins Node based at Colorado State University, Anastasia collaborated  on three separate projects which utilized remote sensing to address environmental and public policy issues. 
  
  In her first project Anastasia worked with an interdisciplinary team of researchers to assist the USDA Agricultural Research Service in improving their species distribution models to further the work of the National Plant Germplasm System. They utilized open source satellite imagery from NASA Earth Observations and the European Space Agency to inform predictive models, improving *in situ* tracking of species not often found in seed banks to bolster food security. In more recent projects, Anastasia served as project lead in a feasibility analysis assisting the National Park Service and USGS to monitor harmful algal blooms in alpine lakes in Rocky Mountain National Park using remote sensing.

  After her time with NASA DEVELOP in Colorado, Anastasia returned to Santa Barbara to pursue her masters degree from the Bren School of Environmental Science and Management, where she is speciealizing in Coastal Marine Resource Management and Conservation Planning. She hopes to improve her skills in spatial analysis and remote sensing to help sustainably manage marine systems. 



